---
title: Analyze organellar DNA transfer in white spruce (Picea glauca)
author: Shaun Jackman
---

```{r load-libraries}
library(dplyr)
library(ggplot2)
library(knitr)
library(magrittr)
library(readr)
library(scales)
```

# Read data
```{r read-data}
nu_cp <- read_tsv("pg29-scaffolds.pg29-plastid.sort.paf.tsv")
nu_mt <- read_tsv("pg29-scaffolds.pg29mt-scaffolds.sort.paf.tsv")
genome_sizes <- data_frame(Organelle = c("cp", "mt"), GenomeSize = c(123266, 5931259))
```

# Munge data
```{r munge-data}
nu_cp <- nu_cp %>% mutate(qalen = qend - qstart, talen = tend - tstart)
nu_mt <- nu_mt %>% mutate(qalen = qend - qstart, talen = tend - tstart)
```

# Summarize data
```{r summarize-data}
data <- bind_rows(
	nu_cp %>% mutate(Organelle = "cp"),
	nu_mt %>% mutate(Organelle = "mt"))
summary <- data %>%
	filter(divergence > 0) %>%
	group_by(Organelle) %>%
	summarize(Segments = n(), Bases = sum(qalen), Divergence = weighted.mean(divergence, qalen)) %>%
	left_join(genome_sizes, by = "Organelle") %>%
	select(Organelle, GenomeSize, everything())
nu_cp_divergence <- summary %>% filter(Organelle == "cp") %$% Divergence
nu_mt_divergence <- summary %>% filter(Organelle == "mt") %$% Divergence
kable(summary)
```

# Count covered bases
```{r count-covered-bases}
vseq <- Vectorize(seq.default, vectorize.args = c("from", "to"))

filter_divergence_and_length <- function(data, alen_threshold)
	data %>% filter(divergence > 0 & qalen >= alen_threshold & talen >= alen_threshold)

count_aligned_bases <- function(data)
	c(nrow(data),
		data %$% vseq(qname * 10000000 + qstart, qname * 10000000 + qend - 1) %>% unlist %>% unique %>% length)

data %>% filter(Organelle == "cp") %>% filter_divergence_and_length(1) %>% count_aligned_bases()
data %>% filter(Organelle == "cp") %>% filter_divergence_and_length(500) %>% count_aligned_bases()
data %>% filter(Organelle == "mt") %>% filter_divergence_and_length(1) %>% count_aligned_bases()
data %>% filter(Organelle == "mt") %>% filter_divergence_and_length(500) %>% count_aligned_bases()

data %>% filter_divergence_and_length(500) %>%
	group_by(Organelle) %>%
	summarize(Segments = n(), Bases = sum(qalen),
		Min_divergence = min(divergence),
		Mean_divergence = weighted.mean(divergence, qalen),
		Max_divergence = max(divergence)) %>%
	left_join(genome_sizes, by = "Organelle") %>%
	select(Organelle, GenomeSize, everything())
```

# Nuclear-plastid query-alignment-length vs divergence
```{r plot-nu-cp-point}
ggplot(nu_cp) +
	aes(x = divergence, y = qalen) +
	geom_point() +
	scale_x_continuous(breaks = pretty_breaks(10))
```

# Nuclear-plastid divergence histogram
```{r plot-nu-cp-divergence-hist}
ggplot(nu_cp) +
	aes(x = divergence, weight = qalen) +
	geom_histogram(binwidth = 0.005) +
	geom_vline(x = nu_cp_divergence) +
	scale_x_continuous(limits = c(0, NA), breaks = pretty_breaks(10))
```

# Nuclear-mitochondrion query-alignment-length vs divergence
```{r plot-nu-mt}
ggplot(nu_mt) +
	aes(x = divergence, y = qalen) +
	geom_point() +
	scale_x_continuous(breaks = pretty_breaks(10))
```

# Nuclear-mitochondrion divergence histogram (log)
```{r plot-nu-mt-divergence-hist-log}
ggplot(nu_mt) +
	aes(x = 0.0001 + divergence, weight = qalen) +
	geom_histogram(binwidth = 0.1) +
	geom_vline(x = nu_mt_divergence) +
	scale_x_log10(breaks = log_breaks(10))
```

# Nuclear-mitochondrion divergence histogram (linear)
```{r plot-nu-mt-divergence-hist}
ggplot(nu_mt) +
	aes(x = divergence, weight = qalen) +
	geom_histogram(binwidth = 0.01) +
	geom_vline(x = nu_mt_divergence) +
	scale_x_continuous(breaks = pretty_breaks(10))
```
